name: Spec-MAS v2.0 Validation Pipeline

on:
  pull_request:
    paths:
      - 'specs/**/*.yaml'
      - 'specs/**/*.md'
  push:
    branches:
      - main
      - develop
    paths:
      - 'specs/**/*.yaml'
      - 'specs/**/*.md'
  workflow_dispatch:
    inputs:
      spec_path:
        description: 'Path to spec file to validate'
        required: false
        type: string

jobs:
  progressive-validation:
    name: Progressive Validation Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
      
      - name: Identify changed specs
        id: changed-specs
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "specs=$(git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -E 'specs/.*\.(yaml|md)$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.spec_path }}" ]; then
            echo "specs=${{ inputs.spec_path }}" >> $GITHUB_OUTPUT
          else
            echo "specs=$(find specs -name '*.yaml' -o -name '*.md' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          fi
      
      - name: Level 1 - Syntax Validation
        id: level1
        run: |
          for spec in ${{ steps.changed-specs.outputs.specs }}; do
            echo "Validating syntax for $spec"
            python specmas/validation/gates.py "$spec" --level 1
          done
      
      - name: Level 2 - Semantic Validation
        id: level2
        if: success()
        run: |
          for spec in ${{ steps.changed-specs.outputs.specs }}; do
            echo "Validating semantics for $spec"
            python specmas/validation/gates.py "$spec" --level 2
          done
      
      - name: Level 3 - Coverage Validation
        id: level3
        if: success()
        run: |
          for spec in ${{ steps.changed-specs.outputs.specs }}; do
            echo "Validating coverage for $spec"
            python specmas/validation/gates.py "$spec" --level 3
          done
      
      - name: Level 4 - Cross-Reference Validation
        id: level4
        if: success()
        run: |
          for spec in ${{ steps.changed-specs.outputs.specs }}; do
            echo "Validating cross-references for $spec"
            python specmas/validation/gates.py "$spec" --level 4
          done
      
      - name: Generate validation report
        if: always()
        run: |
          echo "## Validation Report" > validation-report.md
          echo "" >> validation-report.md
          
          if [ "${{ steps.level1.outcome }}" = "success" ]; then
            echo "✅ Level 1 (Syntax): Passed" >> validation-report.md
          else
            echo "❌ Level 1 (Syntax): Failed" >> validation-report.md
          fi
          
          if [ "${{ steps.level2.outcome }}" = "success" ]; then
            echo "✅ Level 2 (Semantic): Passed" >> validation-report.md
          else
            echo "❌ Level 2 (Semantic): Failed" >> validation-report.md
          fi
          
          if [ "${{ steps.level3.outcome }}" = "success" ]; then
            echo "✅ Level 3 (Coverage): Passed" >> validation-report.md
          else
            echo "❌ Level 3 (Coverage): Failed" >> validation-report.md
          fi
          
          if [ "${{ steps.level4.outcome }}" = "success" ]; then
            echo "✅ Level 4 (Cross-Reference): Passed" >> validation-report.md
          else
            echo "❌ Level 4 (Cross-Reference): Failed" >> validation-report.md
          fi
      
      - name: Post validation results to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('validation-report.md', 'utf8');
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
      
      - name: Mark ready for adversarial review
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready-for-adversarial-review']
            });
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All validation gates passed! Spec is ready for adversarial review.\n\nTo run adversarial review:\n```bash\npython specmas/adversarial/review.py <spec_path>\n```'
            });

  adversarial-review:
    name: Adversarial Review
    runs-on: ubuntu-latest
    needs: progressive-validation
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-adversarial-review')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
      
      - name: Run adversarial review
        id: adversarial
        run: |
          for spec in ${{ needs.progressive-validation.outputs.specs }}; do
            echo "Running adversarial review for $spec"
            python specmas/adversarial/review.py "$spec" > "adversarial-report-$(basename $spec).txt"
          done
      
      - name: Upload adversarial reports
        uses: actions/upload-artifact@v3
        with:
          name: adversarial-reports
          path: adversarial-report-*.txt
      
      - name: Check for critical findings
        run: |
          critical_count=0
          for report in adversarial-report-*.txt; do
            if grep -q "CRITICAL" "$report"; then
              critical_count=$((critical_count + 1))
            fi
          done
          
          if [ $critical_count -gt 0 ]; then
            echo "❌ Found $critical_count critical findings in adversarial review"
            exit 1
          else
            echo "✅ No critical findings in adversarial review"
          fi
      
      - name: Post adversarial results to PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let summary = '## Adversarial Review Results\n\n';
            
            const reportFiles = fs.readdirSync('.').filter(f => f.startsWith('adversarial-report-'));
            
            for (const file of reportFiles) {
              const content = fs.readFileSync(file, 'utf8');
              const specName = file.replace('adversarial-report-', '').replace('.txt', '');
              
              // Extract key metrics from report
              const criticalMatch = content.match(/Critical Findings: (\d+)/);
              const totalMatch = content.match(/Total Findings: (\d+)/);
              const statusMatch = content.match(/Status: (.+)/);
              
              const critical = criticalMatch ? criticalMatch[1] : '0';
              const total = totalMatch ? totalMatch[1] : '0';
              const status = statusMatch ? statusMatch[1] : 'Unknown';
              
              summary += `### ${specName}\n`;
              summary += `- Total Findings: ${total}\n`;
              summary += `- Critical Findings: ${critical}\n`;
              summary += `- Status: ${status}\n\n`;
            }
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: adversarial-review
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run security checks
        run: |
          echo "Running security-specific validation..."
          # Add security scanning tools here
          # - Dependency vulnerability scanning
          # - Static analysis
          # - License compliance
      
      - name: Check for security markers in specs
        run: |
          for spec in specs/**/*.yaml; do
            if grep -q "security_classification: HIGH" "$spec"; then
              echo "High security spec found: $spec"
              echo "Enforcing additional security checks..."
              
              # Check for required security sections
              if ! grep -q "security_requirements:" "$spec"; then
                echo "❌ Missing security_requirements section in high-security spec"
                exit 1
              fi
              
              if ! grep -q "encryption:" "$spec"; then
                echo "❌ Missing encryption requirements in high-security spec"
                exit 1
              fi
              
              if ! grep -q "audit:" "$spec"; then
                echo "❌ Missing audit requirements in high-security spec"
                exit 1
              fi
            fi
          done
